#!/usr/bin/perl
use strict;

my $line;
my ($chars, $width, $height);
my $head = 0;

while (chomp($line = <STDIN>)){
    next if ($line eq '++font-text-file');
    if ($line eq '++chars') { chomp( $chars = <STDIN> ); }
    if ($line eq '++width') { chomp( $width = <STDIN> ); }
    if ($line eq '++height'){ chomp( $height = <STDIN> ); }
    
    if ($chars and $width and $height and not $head){
        print "; DO NOT EDIT THIS FILE BY HAND\n";
        print "; This file has been generated automaticaly by psf2coe utility.\n";
        print "; Original file: lat0-12.txt\n";
        print "; chars: $chars\n";
        print "; char width: $width px\n";
        print "; char height: $height px\n";
        print "memory_initialization_radix  = 2;\n";
        print "memory_initialization_vector =\n";
        $head++;
    }
    
    if ( $line =~ /\+\+---(\d\d\d)-0x(..)-'(.?)'-/ ){
        my ($c_dec, $c_hex, $c) = ($1,$2,$3);
        print "; --- $c_dec - 0x$c_hex - '$c' ---\n";
        for( my $y = 0 ; $y < $height ; $y++ ){
            $line = <STDIN>;
            $line =~ s/ /0 /g;
            $line =~ s/x/1 /gi;
            print $line;
        }
    }
}

print "\n; --- END ---\n";
